//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1022
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmojiLib {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CatFace {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CatFace() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmojiLib.CatFace", typeof(CatFace).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap CatWithTearsOfJoyApple {
            get {
                object obj = ResourceManager.GetObject("CatWithTearsOfJoyApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CatWithTearsOfJoyFacebook {
            get {
                object obj = ResourceManager.GetObject("CatWithTearsOfJoyFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CatWithTearsOfJoyGmail {
            get {
                object obj = ResourceManager.GetObject("CatWithTearsOfJoyGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CatWithTearsOfJoyGoogle {
            get {
                object obj = ResourceManager.GetObject("CatWithTearsOfJoyGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CatWithTearsOfJoyJoyPixels {
            get {
                object obj = ResourceManager.GetObject("CatWithTearsOfJoyJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CatWithTearsOfJoyKddi {
            get {
                object obj = ResourceManager.GetObject("CatWithTearsOfJoyKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CatWithTearsOfJoySamsung {
            get {
                object obj = ResourceManager.GetObject("CatWithTearsOfJoySamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CatWithTearsOfJoyTwitter {
            get {
                object obj = ResourceManager.GetObject("CatWithTearsOfJoyTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CatWithTearsOfJoyWindows {
            get {
                object obj = ResourceManager.GetObject("CatWithTearsOfJoyWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CatWithWrySmileApple {
            get {
                object obj = ResourceManager.GetObject("CatWithWrySmileApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CatWithWrySmileFacebook {
            get {
                object obj = ResourceManager.GetObject("CatWithWrySmileFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CatWithWrySmileGmail {
            get {
                object obj = ResourceManager.GetObject("CatWithWrySmileGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CatWithWrySmileGoogle {
            get {
                object obj = ResourceManager.GetObject("CatWithWrySmileGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CatWithWrySmileJoyPixels {
            get {
                object obj = ResourceManager.GetObject("CatWithWrySmileJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CatWithWrySmileKddi {
            get {
                object obj = ResourceManager.GetObject("CatWithWrySmileKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CatWithWrySmileSamsung {
            get {
                object obj = ResourceManager.GetObject("CatWithWrySmileSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CatWithWrySmileTwitter {
            get {
                object obj = ResourceManager.GetObject("CatWithWrySmileTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CatWithWrySmileWindows {
            get {
                object obj = ResourceManager.GetObject("CatWithWrySmileWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CryingCatApple {
            get {
                object obj = ResourceManager.GetObject("CryingCatApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CryingCatFacebook {
            get {
                object obj = ResourceManager.GetObject("CryingCatFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CryingCatGmail {
            get {
                object obj = ResourceManager.GetObject("CryingCatGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CryingCatGoogle {
            get {
                object obj = ResourceManager.GetObject("CryingCatGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CryingCatJoyPixels {
            get {
                object obj = ResourceManager.GetObject("CryingCatJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CryingCatKddi {
            get {
                object obj = ResourceManager.GetObject("CryingCatKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CryingCatSamsung {
            get {
                object obj = ResourceManager.GetObject("CryingCatSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CryingCatTwitter {
            get {
                object obj = ResourceManager.GetObject("CryingCatTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CryingCatWindows {
            get {
                object obj = ResourceManager.GetObject("CryingCatWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrinningCatApple {
            get {
                object obj = ResourceManager.GetObject("GrinningCatApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrinningCatFacebook {
            get {
                object obj = ResourceManager.GetObject("GrinningCatFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrinningCatGmail {
            get {
                object obj = ResourceManager.GetObject("GrinningCatGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrinningCatGoogle {
            get {
                object obj = ResourceManager.GetObject("GrinningCatGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrinningCatJoyPixels {
            get {
                object obj = ResourceManager.GetObject("GrinningCatJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrinningCatKddi {
            get {
                object obj = ResourceManager.GetObject("GrinningCatKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrinningCatSamsung {
            get {
                object obj = ResourceManager.GetObject("GrinningCatSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrinningCatTwitter {
            get {
                object obj = ResourceManager.GetObject("GrinningCatTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrinningCatWindows {
            get {
                object obj = ResourceManager.GetObject("GrinningCatWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrinningCatWithSmilingEyesApple {
            get {
                object obj = ResourceManager.GetObject("GrinningCatWithSmilingEyesApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrinningCatWithSmilingEyesFacebook {
            get {
                object obj = ResourceManager.GetObject("GrinningCatWithSmilingEyesFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrinningCatWithSmilingEyesGmail {
            get {
                object obj = ResourceManager.GetObject("GrinningCatWithSmilingEyesGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrinningCatWithSmilingEyesGoogle {
            get {
                object obj = ResourceManager.GetObject("GrinningCatWithSmilingEyesGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrinningCatWithSmilingEyesJoyPixels {
            get {
                object obj = ResourceManager.GetObject("GrinningCatWithSmilingEyesJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrinningCatWithSmilingEyesKddi {
            get {
                object obj = ResourceManager.GetObject("GrinningCatWithSmilingEyesKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrinningCatWithSmilingEyesSamsung {
            get {
                object obj = ResourceManager.GetObject("GrinningCatWithSmilingEyesSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrinningCatWithSmilingEyesTwitter {
            get {
                object obj = ResourceManager.GetObject("GrinningCatWithSmilingEyesTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrinningCatWithSmilingEyesWindows {
            get {
                object obj = ResourceManager.GetObject("GrinningCatWithSmilingEyesWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingCatApple {
            get {
                object obj = ResourceManager.GetObject("KissingCatApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingCatFacebook {
            get {
                object obj = ResourceManager.GetObject("KissingCatFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingCatGmail {
            get {
                object obj = ResourceManager.GetObject("KissingCatGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingCatGoogle {
            get {
                object obj = ResourceManager.GetObject("KissingCatGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingCatJoyPixels {
            get {
                object obj = ResourceManager.GetObject("KissingCatJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingCatKddi {
            get {
                object obj = ResourceManager.GetObject("KissingCatKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingCatSamsung {
            get {
                object obj = ResourceManager.GetObject("KissingCatSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingCatTwitter {
            get {
                object obj = ResourceManager.GetObject("KissingCatTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingCatWindows {
            get {
                object obj = ResourceManager.GetObject("KissingCatWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PoutingCatApple {
            get {
                object obj = ResourceManager.GetObject("PoutingCatApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PoutingCatFacebook {
            get {
                object obj = ResourceManager.GetObject("PoutingCatFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PoutingCatGmail {
            get {
                object obj = ResourceManager.GetObject("PoutingCatGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PoutingCatGoogle {
            get {
                object obj = ResourceManager.GetObject("PoutingCatGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PoutingCatJoyPixels {
            get {
                object obj = ResourceManager.GetObject("PoutingCatJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PoutingCatKddi {
            get {
                object obj = ResourceManager.GetObject("PoutingCatKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PoutingCatSamsung {
            get {
                object obj = ResourceManager.GetObject("PoutingCatSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PoutingCatTwitter {
            get {
                object obj = ResourceManager.GetObject("PoutingCatTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PoutingCatWindows {
            get {
                object obj = ResourceManager.GetObject("PoutingCatWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingCatWithHeartEyesApple {
            get {
                object obj = ResourceManager.GetObject("SmilingCatWithHeartEyesApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingCatWithHeartEyesFacebook {
            get {
                object obj = ResourceManager.GetObject("SmilingCatWithHeartEyesFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingCatWithHeartEyesGmail {
            get {
                object obj = ResourceManager.GetObject("SmilingCatWithHeartEyesGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingCatWithHeartEyesGoogle {
            get {
                object obj = ResourceManager.GetObject("SmilingCatWithHeartEyesGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingCatWithHeartEyesJoyPixels {
            get {
                object obj = ResourceManager.GetObject("SmilingCatWithHeartEyesJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingCatWithHeartEyesKddi {
            get {
                object obj = ResourceManager.GetObject("SmilingCatWithHeartEyesKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingCatWithHeartEyesSamsung {
            get {
                object obj = ResourceManager.GetObject("SmilingCatWithHeartEyesSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingCatWithHeartEyesTwitter {
            get {
                object obj = ResourceManager.GetObject("SmilingCatWithHeartEyesTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingCatWithHeartEyesWindows {
            get {
                object obj = ResourceManager.GetObject("SmilingCatWithHeartEyesWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WearyCatApple {
            get {
                object obj = ResourceManager.GetObject("WearyCatApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WearyCatFacebook {
            get {
                object obj = ResourceManager.GetObject("WearyCatFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WearyCatGmail {
            get {
                object obj = ResourceManager.GetObject("WearyCatGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WearyCatGoogle {
            get {
                object obj = ResourceManager.GetObject("WearyCatGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WearyCatJoyPixels {
            get {
                object obj = ResourceManager.GetObject("WearyCatJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WearyCatKddi {
            get {
                object obj = ResourceManager.GetObject("WearyCatKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WearyCatSamsung {
            get {
                object obj = ResourceManager.GetObject("WearyCatSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WearyCatTwitter {
            get {
                object obj = ResourceManager.GetObject("WearyCatTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WearyCatWindows {
            get {
                object obj = ResourceManager.GetObject("WearyCatWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
