using EmojiLib.Properties;

namespace EmojiLib
{
	public static class EmojiSet
	{
		internal static readonly Emoji grinningFace = new Emoji(character: "😀", unicode: "U+1F600", group: Resources.smileysAndEmotion, subGroup: Resources.faceSmiling, shortName: "", fullName: "grinning face", description: "", appleIcon: FaceSmiling.GrinningFaceApple, googleIcon: FaceSmiling.GrinningFaceGoogle, facebookIcon: FaceSmiling.GrinningFaceFacebook, windowsIcon: FaceSmiling.GrinningFaceWindows, twitterIcon: FaceSmiling.GrinningFaceTwitter, joypixelsIcon: FaceSmiling.GrinningFaceJoyPixels, samsungIcon: FaceSmiling.GrinningFaceSamsung, gmailIcon: FaceSmiling.GrinningFaceGmail, docomoIcon: null, kddiIcon: null, softbankIcon: null);
		internal static readonly Emoji grinningFaceWithBigEyes = new Emoji(character: "😃", unicode: "U+1F600", group: Resources.smileysAndEmotion, subGroup: Resources.faceSmiling, shortName: "", fullName: "grinning face with big eyes", description: "", appleIcon: FaceSmiling.GrinningFaceWithBigEyesApple, googleIcon: FaceSmiling.GrinningFaceWithBigEyesGoogle, facebookIcon: FaceSmiling.GrinningFaceWithBigEyesFacebook, windowsIcon: FaceSmiling.GrinningFaceWithBigEyesWindows, twitterIcon: FaceSmiling.GrinningFaceWithBigEyesTwitter, joypixelsIcon: FaceSmiling.GrinningFaceWithBigEyesJoyPixels, samsungIcon: FaceSmiling.GrinningFaceWithBigEyesSamsung, gmailIcon: FaceSmiling.GrinningFaceWithBigEyesGmail, docomoIcon: FaceSmiling.GrinningFaceWithBigEyesDocomo, kddiIcon: FaceSmiling.GrinningFaceWithBigEyesKddi, softbankIcon: FaceSmiling.GrinningFaceWithBigEyesSoftbank);
		internal static readonly Emoji grinningFaceWithSmilingEyes = new Emoji(character: "😄", unicode: "U+1F604", group: Resources.smileysAndEmotion, subGroup: Resources.faceSmiling, shortName: "", fullName: "grinning face with smiling eyes", description: "", appleIcon: FaceSmiling.GrinningFaceWithSmilingEyesApple, googleIcon: FaceSmiling.GrinningFaceWithSmilingEyesGoogle, facebookIcon: FaceSmiling.GrinningFaceWithSmilingEyesFacebook, windowsIcon: FaceSmiling.GrinningFaceWithSmilingEyesWindows, twitterIcon: FaceSmiling.GrinningFaceWithSmilingEyesTwitter, joypixelsIcon: FaceSmiling.GrinningFaceWithSmilingEyesJoyPixels, samsungIcon: FaceSmiling.GrinningFaceWithSmilingEyesSamsung, gmailIcon: FaceSmiling.GrinningFaceWithSmilingEyesGmail, docomoIcon: null, kddiIcon: null, softbankIcon: FaceSmiling.GrinningFaceWithSmilingEyesSoftbank);
		internal static readonly Emoji beamingFaceWithSmilingEyes = new Emoji(character: "😁", unicode: "U+1F601", group: Resources.smileysAndEmotion, subGroup: Resources.faceSmiling, shortName: "", fullName: "beaming face with smiling eyes", description: "", appleIcon: FaceSmiling.BeamingFaceWithSmilingEyesApple, googleIcon: FaceSmiling.BeamingFaceWithSmilingEyesGoogle, facebookIcon: FaceSmiling.BeamingFaceWithSmilingEyesFacebook, windowsIcon: FaceSmiling.BeamingFaceWithSmilingEyesWindows, twitterIcon: FaceSmiling.BeamingFaceWithSmilingEyesTwitter, joypixelsIcon: FaceSmiling.BeamingFaceWithSmilingEyesJoyPixels, samsungIcon: FaceSmiling.BeamingFaceWithSmilingEyesSamsung, gmailIcon: FaceSmiling.BeamingFaceWithSmilingEyesGmail, docomoIcon: FaceSmiling.BeamingFaceWithSmilingEyesDocomo, kddiIcon: FaceSmiling.BeamingFaceWithSmilingEyesKddi, softbankIcon: FaceSmiling.BeamingFaceWithSmilingEyesSoftbank);
		internal static readonly Emoji grinningSquintingFace = new Emoji(character: "😆", unicode: "U+1F606", group: Resources.smileysAndEmotion, subGroup: Resources.faceSmiling, shortName: "", fullName: "grinning squinting face", description: "", appleIcon: FaceSmiling.GrinningSquintingFaceApple, googleIcon: FaceSmiling.GrinningSquintingFaceGoogle, facebookIcon: FaceSmiling.GrinningSquintingFaceFacebook, windowsIcon: FaceSmiling.GrinningSquintingFaceWindows, twitterIcon: FaceSmiling.GrinningSquintingFaceTwitter, joypixelsIcon: FaceSmiling.GrinningSquintingFaceJoyPixels, samsungIcon: FaceSmiling.GrinningSquintingFaceSamsung, gmailIcon: FaceSmiling.GrinningSquintingFaceGmail, docomoIcon: FaceSmiling.GrinningSquintingFaceDocomo, kddiIcon: null, softbankIcon: null);
		internal static readonly Emoji grinningFaceWithSweat = new Emoji(character: "😅", unicode: "U+1F605", group: Resources.smileysAndEmotion, subGroup: Resources.faceSmiling, shortName: "", fullName: "grinning face with sweat", description: "", appleIcon: FaceSmiling.GrinningFaceWithSweatApple, googleIcon: FaceSmiling.GrinningFaceWithSweatGoogle, facebookIcon: FaceSmiling.GrinningFaceWithSweatFacebook, windowsIcon: FaceSmiling.GrinningFaceWithSweatWindows, twitterIcon: FaceSmiling.GrinningFaceWithSweatTwitter, joypixelsIcon: FaceSmiling.GrinningFaceWithSweatJoyPixels, samsungIcon: FaceSmiling.GrinningFaceWithSweatSamsung, gmailIcon: FaceSmiling.GrinningFaceWithSweatGmail, docomoIcon: FaceSmiling.GrinningFaceWithSweatDocomo, kddiIcon: null, softbankIcon: null);
		internal static readonly Emoji rollingOnTheFloorLaughing = new Emoji(character: "🤣", unicode: "U+1F923", group: Resources.smileysAndEmotion, subGroup: Resources.faceSmiling, shortName: "", fullName: "rolling on the floor laughing", description: "", appleIcon: FaceSmiling.RollingOnTheFloorLaughingApple, googleIcon: FaceSmiling.RollingOnTheFloorLaughingGoogle, facebookIcon: FaceSmiling.RollingOnTheFloorLaughingFacebook, windowsIcon: FaceSmiling.RollingOnTheFloorLaughingWindows, twitterIcon: FaceSmiling.RollingOnTheFloorLaughingTwitter, joypixelsIcon: FaceSmiling.RollingOnTheFloorLaughingJoyPixels, samsungIcon: FaceSmiling.RollingOnTheFloorLaughingSamsung, gmailIcon: null, docomoIcon: null, kddiIcon: null, softbankIcon: null);
		internal static readonly Emoji faceWithTearsOfJoy = new Emoji(character: "😂", unicode: "U+1F602", group: Resources.smileysAndEmotion, subGroup: Resources.faceSmiling, shortName: "", fullName: "face with tears of joy", description: "", appleIcon: FaceSmiling.FaceWithTearsOfJoyApple, googleIcon: FaceSmiling.FaceWithTearsOfJoyGoogle, facebookIcon: FaceSmiling.FaceWithTearsOfJoyFacebook, windowsIcon: FaceSmiling.FaceWithTearsOfJoyWindows, twitterIcon: FaceSmiling.FaceWithTearsOfJoyTwitter, joypixelsIcon: FaceSmiling.FaceWithTearsOfJoyJoyPixels, samsungIcon: FaceSmiling.FaceWithTearsOfJoySamsung, gmailIcon: FaceSmiling.FaceWithTearsOfJoyGmail, docomoIcon: null, kddiIcon: FaceSmiling.FaceWithTearsOfJoyKddi, softbankIcon: FaceSmiling.FaceWithTearsOfJoySoftbank);
		internal static readonly Emoji slightlySmilingFace = new Emoji(character: "🙂", unicode: "U+1F642", group: Resources.smileysAndEmotion, subGroup: Resources.faceSmiling, shortName: "", fullName: "slightly smiling face", description: "", appleIcon: FaceSmiling.SlightlySmilingFaceApple, googleIcon: FaceSmiling.SlightlySmilingFaceGoogle, facebookIcon: FaceSmiling.SlightlySmilingFaceFacebook, windowsIcon: FaceSmiling.SlightlySmilingFaceWindows, twitterIcon: FaceSmiling.SlightlySmilingFaceTwitter, joypixelsIcon: FaceSmiling.SlightlySmilingFaceJoyPixels, samsungIcon: FaceSmiling.SlightlySmilingFaceSamsung, gmailIcon: FaceSmiling.SlightlySmilingFaceGmail, docomoIcon: null, kddiIcon: null, softbankIcon: null);
		internal static readonly Emoji upsideDownFace = new Emoji(character: "🙃", unicode: "U+1F643", group: Resources.smileysAndEmotion, subGroup: Resources.faceSmiling, shortName: "", fullName: "upside-down face", description: "", appleIcon: FaceSmiling.UpsideDownFaceApple, googleIcon: FaceSmiling.UpsideDownFaceGoogle, facebookIcon: FaceSmiling.UpsideDownFaceFacebook, windowsIcon: FaceSmiling.UpsideDownFaceWindows, twitterIcon: FaceSmiling.UpsideDownFaceTwitter, joypixelsIcon: FaceSmiling.UpsideDownFaceJoyPixels, samsungIcon: FaceSmiling.UpsideDownFaceSamsung, gmailIcon: null, docomoIcon: null, kddiIcon: null, softbankIcon: null);
		internal static readonly Emoji winkingFace = new Emoji(character: "😉", unicode: "U+1F609", group: Resources.smileysAndEmotion, subGroup: Resources.faceSmiling, shortName: "", fullName: "winking face", description: "", appleIcon: FaceSmiling.WinkingFaceApple, googleIcon: FaceSmiling.WinkingFaceGoogle, facebookIcon: FaceSmiling.WinkingFaceFacebook, windowsIcon: FaceSmiling.WinkingFaceWindows, twitterIcon: FaceSmiling.WinkingFaceTwitter, joypixelsIcon: FaceSmiling.WinkingFaceJoyPixels, samsungIcon: FaceSmiling.WinkingFaceSamsung, gmailIcon: FaceSmiling.WinkingFaceGmail, docomoIcon: FaceSmiling.WinkingFaceDocomo, kddiIcon: FaceSmiling.WinkingFaceKddi, softbankIcon: FaceSmiling.WinkingFaceSoftbank);
		internal static readonly Emoji smilingFaceWithSmilingEyes = new Emoji(character: "😊", unicode: "U+1F60A", group: Resources.smileysAndEmotion, subGroup: Resources.faceSmiling, shortName: "", fullName: "smiling face with smiling eyes", description: "", appleIcon: FaceSmiling.SmilingFaceWithSmilingEyesApple, googleIcon: FaceSmiling.SmilingFaceWithSmilingEyesGoogle, facebookIcon: FaceSmiling.SmilingFaceWithSmilingEyesFacebook, windowsIcon: FaceSmiling.SmilingFaceWithSmilingEyesWindows, twitterIcon: FaceSmiling.SmilingFaceWithSmilingEyesTwitter, joypixelsIcon: FaceSmiling.SmilingFaceWithSmilingEyesJoyPixels, samsungIcon: FaceSmiling.SmilingFaceWithSmilingEyesSamsung, gmailIcon: FaceSmiling.SmilingFaceWithSmilingEyesGmail, docomoIcon: null, kddiIcon: FaceSmiling.SmilingFaceWithSmilingEyesKddi, softbankIcon: FaceSmiling.SmilingFaceWithSmilingEyesSoftbank);
		internal static readonly Emoji smilingFaceWithHalo = new Emoji(character: "😇", unicode: "U+1F607", group: Resources.smileysAndEmotion, subGroup: Resources.faceSmiling, shortName: "", fullName: "smiling face with halo", description: "", appleIcon: FaceSmiling.SmilingFaceWithHaloApple, googleIcon: FaceSmiling.SmilingFaceWithHaloGoogle, facebookIcon: FaceSmiling.SmilingFaceWithHaloFacebook, windowsIcon: FaceSmiling.SmilingFaceWithHaloWindows, twitterIcon: FaceSmiling.SmilingFaceWithHaloTwitter, joypixelsIcon: FaceSmiling.SmilingFaceWithHaloJoyPixels, samsungIcon: FaceSmiling.SmilingFaceWithHaloSamsung, gmailIcon: null, docomoIcon: null, kddiIcon: null, softbankIcon: null);
	}
}