//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1022
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmojiLib {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FaceConcerned {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FaceConcerned() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmojiLib.FaceConcerned", typeof(FaceConcerned).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AnguishedFaceApple {
            get {
                object obj = ResourceManager.GetObject("AnguishedFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnguishedFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("AnguishedFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnguishedFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("AnguishedFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnguishedFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("AnguishedFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnguishedFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("AnguishedFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnguishedFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("AnguishedFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnguishedFaceWindows {
            get {
                object obj = ResourceManager.GetObject("AnguishedFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnxiousFaceWithSweatApple {
            get {
                object obj = ResourceManager.GetObject("AnxiousFaceWithSweatApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnxiousFaceWithSweatFacebook {
            get {
                object obj = ResourceManager.GetObject("AnxiousFaceWithSweatFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnxiousFaceWithSweatGmail {
            get {
                object obj = ResourceManager.GetObject("AnxiousFaceWithSweatGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnxiousFaceWithSweatGoogle {
            get {
                object obj = ResourceManager.GetObject("AnxiousFaceWithSweatGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnxiousFaceWithSweatJoyPixels {
            get {
                object obj = ResourceManager.GetObject("AnxiousFaceWithSweatJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnxiousFaceWithSweatKddi {
            get {
                object obj = ResourceManager.GetObject("AnxiousFaceWithSweatKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnxiousFaceWithSweatSamsung {
            get {
                object obj = ResourceManager.GetObject("AnxiousFaceWithSweatSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnxiousFaceWithSweatSoftbank {
            get {
                object obj = ResourceManager.GetObject("AnxiousFaceWithSweatSoftbank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnxiousFaceWithSweatTwitter {
            get {
                object obj = ResourceManager.GetObject("AnxiousFaceWithSweatTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnxiousFaceWithSweatWindows {
            get {
                object obj = ResourceManager.GetObject("AnxiousFaceWithSweatWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AstonishedFaceApple {
            get {
                object obj = ResourceManager.GetObject("AstonishedFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AstonishedFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("AstonishedFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AstonishedFaceGmail {
            get {
                object obj = ResourceManager.GetObject("AstonishedFaceGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AstonishedFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("AstonishedFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AstonishedFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("AstonishedFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AstonishedFaceKddi {
            get {
                object obj = ResourceManager.GetObject("AstonishedFaceKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AstonishedFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("AstonishedFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AstonishedFaceSoftbank {
            get {
                object obj = ResourceManager.GetObject("AstonishedFaceSoftbank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AstonishedFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("AstonishedFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AstonishedFaceWindows {
            get {
                object obj = ResourceManager.GetObject("AstonishedFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConfoundedFaceApple {
            get {
                object obj = ResourceManager.GetObject("ConfoundedFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConfoundedFaceDocomo {
            get {
                object obj = ResourceManager.GetObject("ConfoundedFaceDocomo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConfoundedFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("ConfoundedFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConfoundedFaceGmail {
            get {
                object obj = ResourceManager.GetObject("ConfoundedFaceGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConfoundedFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("ConfoundedFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConfoundedFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("ConfoundedFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConfoundedFaceKddi {
            get {
                object obj = ResourceManager.GetObject("ConfoundedFaceKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConfoundedFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("ConfoundedFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConfoundedFaceSoftbank {
            get {
                object obj = ResourceManager.GetObject("ConfoundedFaceSoftbank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConfoundedFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("ConfoundedFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConfoundedFaceWindows {
            get {
                object obj = ResourceManager.GetObject("ConfoundedFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConfusedFaceApple {
            get {
                object obj = ResourceManager.GetObject("ConfusedFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConfusedFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("ConfusedFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConfusedFaceGmail {
            get {
                object obj = ResourceManager.GetObject("ConfusedFaceGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConfusedFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("ConfusedFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConfusedFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("ConfusedFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConfusedFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("ConfusedFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConfusedFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("ConfusedFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConfusedFaceWindows {
            get {
                object obj = ResourceManager.GetObject("ConfusedFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CryingFaceApple {
            get {
                object obj = ResourceManager.GetObject("CryingFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CryingFaceDocomo {
            get {
                object obj = ResourceManager.GetObject("CryingFaceDocomo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CryingFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("CryingFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CryingFaceGmail {
            get {
                object obj = ResourceManager.GetObject("CryingFaceGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CryingFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("CryingFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CryingFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("CryingFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CryingFaceKddi {
            get {
                object obj = ResourceManager.GetObject("CryingFaceKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CryingFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("CryingFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CryingFaceSoftbank {
            get {
                object obj = ResourceManager.GetObject("CryingFaceSoftbank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CryingFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("CryingFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CryingFaceWindows {
            get {
                object obj = ResourceManager.GetObject("CryingFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DisappointedFaceApple {
            get {
                object obj = ResourceManager.GetObject("DisappointedFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DisappointedFaceDocomo {
            get {
                object obj = ResourceManager.GetObject("DisappointedFaceDocomo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DisappointedFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("DisappointedFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DisappointedFaceGmail {
            get {
                object obj = ResourceManager.GetObject("DisappointedFaceGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DisappointedFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("DisappointedFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DisappointedFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("DisappointedFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DisappointedFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("DisappointedFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DisappointedFaceSoftbank {
            get {
                object obj = ResourceManager.GetObject("DisappointedFaceSoftbank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DisappointedFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("DisappointedFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DisappointedFaceWindows {
            get {
                object obj = ResourceManager.GetObject("DisappointedFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DowncastFaceWithSweatApple {
            get {
                object obj = ResourceManager.GetObject("DowncastFaceWithSweatApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DowncastFaceWithSweatDocomo {
            get {
                object obj = ResourceManager.GetObject("DowncastFaceWithSweatDocomo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DowncastFaceWithSweatFacebook {
            get {
                object obj = ResourceManager.GetObject("DowncastFaceWithSweatFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DowncastFaceWithSweatGmail {
            get {
                object obj = ResourceManager.GetObject("DowncastFaceWithSweatGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DowncastFaceWithSweatGoogle {
            get {
                object obj = ResourceManager.GetObject("DowncastFaceWithSweatGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DowncastFaceWithSweatJoyPixels {
            get {
                object obj = ResourceManager.GetObject("DowncastFaceWithSweatJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DowncastFaceWithSweatKddi {
            get {
                object obj = ResourceManager.GetObject("DowncastFaceWithSweatKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DowncastFaceWithSweatSamsung {
            get {
                object obj = ResourceManager.GetObject("DowncastFaceWithSweatSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DowncastFaceWithSweatSoftbank {
            get {
                object obj = ResourceManager.GetObject("DowncastFaceWithSweatSoftbank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DowncastFaceWithSweatTwitter {
            get {
                object obj = ResourceManager.GetObject("DowncastFaceWithSweatTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DowncastFaceWithSweatWindows {
            get {
                object obj = ResourceManager.GetObject("DowncastFaceWithSweatWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceScreamingInFearApple {
            get {
                object obj = ResourceManager.GetObject("FaceScreamingInFearApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceScreamingInFearDocomo {
            get {
                object obj = ResourceManager.GetObject("FaceScreamingInFearDocomo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceScreamingInFearFacebook {
            get {
                object obj = ResourceManager.GetObject("FaceScreamingInFearFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceScreamingInFearGmail {
            get {
                object obj = ResourceManager.GetObject("FaceScreamingInFearGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceScreamingInFearGoogle {
            get {
                object obj = ResourceManager.GetObject("FaceScreamingInFearGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceScreamingInFearJoyPixels {
            get {
                object obj = ResourceManager.GetObject("FaceScreamingInFearJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceScreamingInFearKddi {
            get {
                object obj = ResourceManager.GetObject("FaceScreamingInFearKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceScreamingInFearSamsung {
            get {
                object obj = ResourceManager.GetObject("FaceScreamingInFearSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceScreamingInFearSoftbank {
            get {
                object obj = ResourceManager.GetObject("FaceScreamingInFearSoftbank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceScreamingInFearTwitter {
            get {
                object obj = ResourceManager.GetObject("FaceScreamingInFearTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceScreamingInFearWindows {
            get {
                object obj = ResourceManager.GetObject("FaceScreamingInFearWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithOpenMouthApple {
            get {
                object obj = ResourceManager.GetObject("FaceWithOpenMouthApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithOpenMouthFacebook {
            get {
                object obj = ResourceManager.GetObject("FaceWithOpenMouthFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithOpenMouthGoogle {
            get {
                object obj = ResourceManager.GetObject("FaceWithOpenMouthGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithOpenMouthJoyPixels {
            get {
                object obj = ResourceManager.GetObject("FaceWithOpenMouthJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithOpenMouthSamsung {
            get {
                object obj = ResourceManager.GetObject("FaceWithOpenMouthSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithOpenMouthTwitter {
            get {
                object obj = ResourceManager.GetObject("FaceWithOpenMouthTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithOpenMouthWindows {
            get {
                object obj = ResourceManager.GetObject("FaceWithOpenMouthWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FearfulFaceApple {
            get {
                object obj = ResourceManager.GetObject("FearfulFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FearfulFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("FearfulFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FearfulFaceGmail {
            get {
                object obj = ResourceManager.GetObject("FearfulFaceGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FearfulFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("FearfulFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FearfulFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("FearfulFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FearfulFaceKddi {
            get {
                object obj = ResourceManager.GetObject("FearfulFaceKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FearfulFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("FearfulFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FearfulFaceSoftbank {
            get {
                object obj = ResourceManager.GetObject("FearfulFaceSoftbank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FearfulFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("FearfulFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FearfulFaceWindows {
            get {
                object obj = ResourceManager.GetObject("FearfulFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FlushedFaceApple {
            get {
                object obj = ResourceManager.GetObject("FlushedFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FlushedFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("FlushedFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FlushedFaceGmail {
            get {
                object obj = ResourceManager.GetObject("FlushedFaceGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FlushedFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("FlushedFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FlushedFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("FlushedFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FlushedFaceKddi {
            get {
                object obj = ResourceManager.GetObject("FlushedFaceKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FlushedFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("FlushedFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FlushedFaceSoftbank {
            get {
                object obj = ResourceManager.GetObject("FlushedFaceSoftbank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FlushedFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("FlushedFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FlushedFaceWindows {
            get {
                object obj = ResourceManager.GetObject("FlushedFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrowningFaceApple {
            get {
                object obj = ResourceManager.GetObject("FrowningFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrowningFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("FrowningFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrowningFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("FrowningFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrowningFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("FrowningFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrowningFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("FrowningFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrowningFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("FrowningFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrowningFaceWindows {
            get {
                object obj = ResourceManager.GetObject("FrowningFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrowningFaceWithOpenMouthApple {
            get {
                object obj = ResourceManager.GetObject("FrowningFaceWithOpenMouthApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrowningFaceWithOpenMouthFacebook {
            get {
                object obj = ResourceManager.GetObject("FrowningFaceWithOpenMouthFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrowningFaceWithOpenMouthGoogle {
            get {
                object obj = ResourceManager.GetObject("FrowningFaceWithOpenMouthGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrowningFaceWithOpenMouthJoyPixels {
            get {
                object obj = ResourceManager.GetObject("FrowningFaceWithOpenMouthJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrowningFaceWithOpenMouthSamsung {
            get {
                object obj = ResourceManager.GetObject("FrowningFaceWithOpenMouthSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrowningFaceWithOpenMouthTwitter {
            get {
                object obj = ResourceManager.GetObject("FrowningFaceWithOpenMouthTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrowningFaceWithOpenMouthWindows {
            get {
                object obj = ResourceManager.GetObject("FrowningFaceWithOpenMouthWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HushedFaceApple {
            get {
                object obj = ResourceManager.GetObject("HushedFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HushedFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("HushedFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HushedFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("HushedFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HushedFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("HushedFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HushedFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("HushedFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HushedFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("HushedFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HushedFaceWindows {
            get {
                object obj = ResourceManager.GetObject("HushedFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LoudlyCryingFaceApple {
            get {
                object obj = ResourceManager.GetObject("LoudlyCryingFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LoudlyCryingFaceDocomo {
            get {
                object obj = ResourceManager.GetObject("LoudlyCryingFaceDocomo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LoudlyCryingFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("LoudlyCryingFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LoudlyCryingFaceGmail {
            get {
                object obj = ResourceManager.GetObject("LoudlyCryingFaceGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LoudlyCryingFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("LoudlyCryingFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LoudlyCryingFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("LoudlyCryingFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LoudlyCryingFaceKddi {
            get {
                object obj = ResourceManager.GetObject("LoudlyCryingFaceKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LoudlyCryingFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("LoudlyCryingFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LoudlyCryingFaceSoftbank {
            get {
                object obj = ResourceManager.GetObject("LoudlyCryingFaceSoftbank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LoudlyCryingFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("LoudlyCryingFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LoudlyCryingFaceWindows {
            get {
                object obj = ResourceManager.GetObject("LoudlyCryingFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PerseveringFaceApple {
            get {
                object obj = ResourceManager.GetObject("PerseveringFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PerseveringFaceDocomo {
            get {
                object obj = ResourceManager.GetObject("PerseveringFaceDocomo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PerseveringFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("PerseveringFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PerseveringFaceGmail {
            get {
                object obj = ResourceManager.GetObject("PerseveringFaceGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PerseveringFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("PerseveringFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PerseveringFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("PerseveringFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PerseveringFaceKddi {
            get {
                object obj = ResourceManager.GetObject("PerseveringFaceKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PerseveringFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("PerseveringFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PerseveringFaceSoftbank {
            get {
                object obj = ResourceManager.GetObject("PerseveringFaceSoftbank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PerseveringFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("PerseveringFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PerseveringFaceWindows {
            get {
                object obj = ResourceManager.GetObject("PerseveringFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PleadingFaceApple {
            get {
                object obj = ResourceManager.GetObject("PleadingFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PleadingFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("PleadingFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PleadingFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("PleadingFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PleadingFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("PleadingFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PleadingFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("PleadingFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PleadingFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("PleadingFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PleadingFaceWindows {
            get {
                object obj = ResourceManager.GetObject("PleadingFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SadButRelievedFaceApple {
            get {
                object obj = ResourceManager.GetObject("SadButRelievedFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SadButRelievedFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("SadButRelievedFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SadButRelievedFaceGmail {
            get {
                object obj = ResourceManager.GetObject("SadButRelievedFaceGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SadButRelievedFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("SadButRelievedFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SadButRelievedFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("SadButRelievedFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SadButRelievedFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("SadButRelievedFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SadButRelievedFaceSoftbank {
            get {
                object obj = ResourceManager.GetObject("SadButRelievedFaceSoftbank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SadButRelievedFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("SadButRelievedFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SadButRelievedFaceWindows {
            get {
                object obj = ResourceManager.GetObject("SadButRelievedFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SlightlyFrowningFaceApple {
            get {
                object obj = ResourceManager.GetObject("SlightlyFrowningFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SlightlyFrowningFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("SlightlyFrowningFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SlightlyFrowningFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("SlightlyFrowningFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SlightlyFrowningFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("SlightlyFrowningFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SlightlyFrowningFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("SlightlyFrowningFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SlightlyFrowningFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("SlightlyFrowningFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SlightlyFrowningFaceWindows {
            get {
                object obj = ResourceManager.GetObject("SlightlyFrowningFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TiredFaceApple {
            get {
                object obj = ResourceManager.GetObject("TiredFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TiredFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("TiredFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TiredFaceGmail {
            get {
                object obj = ResourceManager.GetObject("TiredFaceGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TiredFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("TiredFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TiredFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("TiredFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TiredFaceKddi {
            get {
                object obj = ResourceManager.GetObject("TiredFaceKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TiredFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("TiredFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TiredFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("TiredFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TiredFaceWindows {
            get {
                object obj = ResourceManager.GetObject("TiredFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WearyFaceApple {
            get {
                object obj = ResourceManager.GetObject("WearyFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WearyFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("WearyFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WearyFaceGmail {
            get {
                object obj = ResourceManager.GetObject("WearyFaceGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WearyFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("WearyFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WearyFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("WearyFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WearyFaceKddi {
            get {
                object obj = ResourceManager.GetObject("WearyFaceKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WearyFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("WearyFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WearyFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("WearyFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WearyFaceWindows {
            get {
                object obj = ResourceManager.GetObject("WearyFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WorriedFaceApple {
            get {
                object obj = ResourceManager.GetObject("WorriedFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WorriedFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("WorriedFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WorriedFaceGmail {
            get {
                object obj = ResourceManager.GetObject("WorriedFaceGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WorriedFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("WorriedFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WorriedFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("WorriedFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WorriedFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("WorriedFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WorriedFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("WorriedFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WorriedFaceWindows {
            get {
                object obj = ResourceManager.GetObject("WorriedFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YawningFaceApple {
            get {
                object obj = ResourceManager.GetObject("YawningFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YawningFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("YawningFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YawningFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("YawningFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YawningFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("YawningFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YawningFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("YawningFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YawningFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("YawningFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YawningFaceWindows {
            get {
                object obj = ResourceManager.GetObject("YawningFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
