//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1022
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmojiLib {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FaceCostume {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FaceCostume() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmojiLib.FaceCostume", typeof(FaceCostume).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AlienApple {
            get {
                object obj = ResourceManager.GetObject("AlienApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlienFacebook {
            get {
                object obj = ResourceManager.GetObject("AlienFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlienGmail {
            get {
                object obj = ResourceManager.GetObject("AlienGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlienGoogle {
            get {
                object obj = ResourceManager.GetObject("AlienGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlienJoyPixels {
            get {
                object obj = ResourceManager.GetObject("AlienJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlienKddi {
            get {
                object obj = ResourceManager.GetObject("AlienKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlienMonsterApple {
            get {
                object obj = ResourceManager.GetObject("AlienMonsterApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlienMonsterFacebook {
            get {
                object obj = ResourceManager.GetObject("AlienMonsterFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlienMonsterGmail {
            get {
                object obj = ResourceManager.GetObject("AlienMonsterGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlienMonsterGoogle {
            get {
                object obj = ResourceManager.GetObject("AlienMonsterGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlienMonsterJoyPixels {
            get {
                object obj = ResourceManager.GetObject("AlienMonsterJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlienMonsterKddi {
            get {
                object obj = ResourceManager.GetObject("AlienMonsterKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlienMonsterSamsung {
            get {
                object obj = ResourceManager.GetObject("AlienMonsterSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlienMonsterSoftbank {
            get {
                object obj = ResourceManager.GetObject("AlienMonsterSoftbank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlienMonsterTwitter {
            get {
                object obj = ResourceManager.GetObject("AlienMonsterTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlienMonsterWindows {
            get {
                object obj = ResourceManager.GetObject("AlienMonsterWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlienSamsung {
            get {
                object obj = ResourceManager.GetObject("AlienSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlienSoftbank {
            get {
                object obj = ResourceManager.GetObject("AlienSoftbank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlienTwitter {
            get {
                object obj = ResourceManager.GetObject("AlienTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlienWindows {
            get {
                object obj = ResourceManager.GetObject("AlienWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClownFaceApple {
            get {
                object obj = ResourceManager.GetObject("ClownFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClownFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("ClownFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClownFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("ClownFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClownFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("ClownFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClownFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("ClownFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClownFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("ClownFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClownFaceWindows {
            get {
                object obj = ResourceManager.GetObject("ClownFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GhostApple {
            get {
                object obj = ResourceManager.GetObject("GhostApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GhostFacebook {
            get {
                object obj = ResourceManager.GetObject("GhostFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GhostGmail {
            get {
                object obj = ResourceManager.GetObject("GhostGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GhostGoogle {
            get {
                object obj = ResourceManager.GetObject("GhostGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GhostJoyPixels {
            get {
                object obj = ResourceManager.GetObject("GhostJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GhostKddi {
            get {
                object obj = ResourceManager.GetObject("GhostKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GhostSamsung {
            get {
                object obj = ResourceManager.GetObject("GhostSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GhostSoftbank {
            get {
                object obj = ResourceManager.GetObject("GhostSoftbank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GhostTwitter {
            get {
                object obj = ResourceManager.GetObject("GhostTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GhostWindows {
            get {
                object obj = ResourceManager.GetObject("GhostWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoblinApple {
            get {
                object obj = ResourceManager.GetObject("GoblinApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoblinFacebook {
            get {
                object obj = ResourceManager.GetObject("GoblinFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoblinGmail {
            get {
                object obj = ResourceManager.GetObject("GoblinGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoblinGoogle {
            get {
                object obj = ResourceManager.GetObject("GoblinGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoblinJoyPixels {
            get {
                object obj = ResourceManager.GetObject("GoblinJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoblinKddi {
            get {
                object obj = ResourceManager.GetObject("GoblinKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoblinSamsung {
            get {
                object obj = ResourceManager.GetObject("GoblinSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoblinTwitter {
            get {
                object obj = ResourceManager.GetObject("GoblinTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoblinWindows {
            get {
                object obj = ResourceManager.GetObject("GoblinWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OgreApple {
            get {
                object obj = ResourceManager.GetObject("OgreApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OgreFacebook {
            get {
                object obj = ResourceManager.GetObject("OgreFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OgreGmail {
            get {
                object obj = ResourceManager.GetObject("OgreGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OgreGoogle {
            get {
                object obj = ResourceManager.GetObject("OgreGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OgreJoyPixels {
            get {
                object obj = ResourceManager.GetObject("OgreJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OgreKddi {
            get {
                object obj = ResourceManager.GetObject("OgreKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OgreSamsung {
            get {
                object obj = ResourceManager.GetObject("OgreSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OgreTwitter {
            get {
                object obj = ResourceManager.GetObject("OgreTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OgreWindows {
            get {
                object obj = ResourceManager.GetObject("OgreWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PileOfPooApple {
            get {
                object obj = ResourceManager.GetObject("PileOfPooApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PileOfPooFacebook {
            get {
                object obj = ResourceManager.GetObject("PileOfPooFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PileOfPooGmail {
            get {
                object obj = ResourceManager.GetObject("PileOfPooGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PileOfPooGoogle {
            get {
                object obj = ResourceManager.GetObject("PileOfPooGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PileOfPooJoyPixels {
            get {
                object obj = ResourceManager.GetObject("PileOfPooJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PileOfPooKddi {
            get {
                object obj = ResourceManager.GetObject("PileOfPooKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PileOfPooSamsung {
            get {
                object obj = ResourceManager.GetObject("PileOfPooSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PileOfPooSoftbank {
            get {
                object obj = ResourceManager.GetObject("PileOfPooSoftbank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PileOfPooTwitter {
            get {
                object obj = ResourceManager.GetObject("PileOfPooTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PileOfPooWindows {
            get {
                object obj = ResourceManager.GetObject("PileOfPooWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RobotApple {
            get {
                object obj = ResourceManager.GetObject("RobotApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RobotFacebook {
            get {
                object obj = ResourceManager.GetObject("RobotFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RobotGoogle {
            get {
                object obj = ResourceManager.GetObject("RobotGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RobotJoyPixels {
            get {
                object obj = ResourceManager.GetObject("RobotJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RobotSamsung {
            get {
                object obj = ResourceManager.GetObject("RobotSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RobotTwitter {
            get {
                object obj = ResourceManager.GetObject("RobotTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RobotWindows {
            get {
                object obj = ResourceManager.GetObject("RobotWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
