//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1022
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmojiLib {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FaceHand {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FaceHand() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmojiLib.FaceHand", typeof(FaceHand).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithHandOverMouthApple {
            get {
                object obj = ResourceManager.GetObject("FaceWithHandOverMouthApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithHandOverMouthFacebook {
            get {
                object obj = ResourceManager.GetObject("FaceWithHandOverMouthFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithHandOverMouthGoogle {
            get {
                object obj = ResourceManager.GetObject("FaceWithHandOverMouthGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithHandOverMouthJoyPixels {
            get {
                object obj = ResourceManager.GetObject("FaceWithHandOverMouthJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithHandOverMouthSamsung {
            get {
                object obj = ResourceManager.GetObject("FaceWithHandOverMouthSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithHandOverMouthTwitter {
            get {
                object obj = ResourceManager.GetObject("FaceWithHandOverMouthTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithHandOverMouthWindows {
            get {
                object obj = ResourceManager.GetObject("FaceWithHandOverMouthWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HuggingFaceApple {
            get {
                object obj = ResourceManager.GetObject("HuggingFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HuggingFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("HuggingFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HuggingFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("HuggingFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HuggingFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("HuggingFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HuggingFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("HuggingFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HuggingFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("HuggingFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HuggingFaceWindows {
            get {
                object obj = ResourceManager.GetObject("HuggingFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ShushingFaceApple {
            get {
                object obj = ResourceManager.GetObject("ShushingFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ShushingFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("ShushingFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ShushingFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("ShushingFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ShushingFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("ShushingFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ShushingFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("ShushingFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ShushingFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("ShushingFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ShushingFaceWindows {
            get {
                object obj = ResourceManager.GetObject("ShushingFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ThinkingFaceApple {
            get {
                object obj = ResourceManager.GetObject("ThinkingFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ThinkingFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("ThinkingFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ThinkingFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("ThinkingFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ThinkingFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("ThinkingFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ThinkingFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("ThinkingFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ThinkingFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("ThinkingFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ThinkingFaceWindows {
            get {
                object obj = ResourceManager.GetObject("ThinkingFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
