//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1022
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmojiLib {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FaceUnwell {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FaceUnwell() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmojiLib.FaceUnwell", typeof(FaceUnwell).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ColdFaceApple {
            get {
                object obj = ResourceManager.GetObject("ColdFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ColdFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("ColdFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ColdFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("ColdFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ColdFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("ColdFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ColdFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("ColdFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ColdFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("ColdFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ColdFaceWindows {
            get {
                object obj = ResourceManager.GetObject("ColdFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DizzyFaceApple {
            get {
                object obj = ResourceManager.GetObject("DizzyFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DizzyFaceDocomo {
            get {
                object obj = ResourceManager.GetObject("DizzyFaceDocomo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DizzyFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("DizzyFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DizzyFaceGmail {
            get {
                object obj = ResourceManager.GetObject("DizzyFaceGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DizzyFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("DizzyFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DizzyFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("DizzyFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DizzyFaceKddi {
            get {
                object obj = ResourceManager.GetObject("DizzyFaceKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DizzyFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("DizzyFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DizzyFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("DizzyFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DizzyFaceWindows {
            get {
                object obj = ResourceManager.GetObject("DizzyFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExplodingHeadApple {
            get {
                object obj = ResourceManager.GetObject("ExplodingHeadApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExplodingHeadFacebook {
            get {
                object obj = ResourceManager.GetObject("ExplodingHeadFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExplodingHeadGoogle {
            get {
                object obj = ResourceManager.GetObject("ExplodingHeadGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExplodingHeadJoyPixels {
            get {
                object obj = ResourceManager.GetObject("ExplodingHeadJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExplodingHeadSamsung {
            get {
                object obj = ResourceManager.GetObject("ExplodingHeadSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExplodingHeadTwitter {
            get {
                object obj = ResourceManager.GetObject("ExplodingHeadTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExplodingHeadWindows {
            get {
                object obj = ResourceManager.GetObject("ExplodingHeadWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceVomitingApple {
            get {
                object obj = ResourceManager.GetObject("FaceVomitingApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceVomitingFacebook {
            get {
                object obj = ResourceManager.GetObject("FaceVomitingFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceVomitingGoogle {
            get {
                object obj = ResourceManager.GetObject("FaceVomitingGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceVomitingJoyPixels {
            get {
                object obj = ResourceManager.GetObject("FaceVomitingJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceVomitingSamsung {
            get {
                object obj = ResourceManager.GetObject("FaceVomitingSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceVomitingTwitter {
            get {
                object obj = ResourceManager.GetObject("FaceVomitingTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceVomitingWindows {
            get {
                object obj = ResourceManager.GetObject("FaceVomitingWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithHeadBandageApple {
            get {
                object obj = ResourceManager.GetObject("FaceWithHeadBandageApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithHeadBandageFacebook {
            get {
                object obj = ResourceManager.GetObject("FaceWithHeadBandageFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithHeadBandageGoogle {
            get {
                object obj = ResourceManager.GetObject("FaceWithHeadBandageGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithHeadBandageJoyPixels {
            get {
                object obj = ResourceManager.GetObject("FaceWithHeadBandageJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithHeadBandageSamsung {
            get {
                object obj = ResourceManager.GetObject("FaceWithHeadBandageSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithHeadBandageTwitter {
            get {
                object obj = ResourceManager.GetObject("FaceWithHeadBandageTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithHeadBandageWindows {
            get {
                object obj = ResourceManager.GetObject("FaceWithHeadBandageWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithMedicalMaskApple {
            get {
                object obj = ResourceManager.GetObject("FaceWithMedicalMaskApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithMedicalMaskFacebook {
            get {
                object obj = ResourceManager.GetObject("FaceWithMedicalMaskFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithMedicalMaskGmail {
            get {
                object obj = ResourceManager.GetObject("FaceWithMedicalMaskGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithMedicalMaskGoogle {
            get {
                object obj = ResourceManager.GetObject("FaceWithMedicalMaskGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithMedicalMaskJoyPixels {
            get {
                object obj = ResourceManager.GetObject("FaceWithMedicalMaskJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithMedicalMaskKddi {
            get {
                object obj = ResourceManager.GetObject("FaceWithMedicalMaskKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithMedicalMaskSamsung {
            get {
                object obj = ResourceManager.GetObject("FaceWithMedicalMaskSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithMedicalMaskSoftbank {
            get {
                object obj = ResourceManager.GetObject("FaceWithMedicalMaskSoftbank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithMedicalMaskTwitter {
            get {
                object obj = ResourceManager.GetObject("FaceWithMedicalMaskTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithMedicalMaskWindows {
            get {
                object obj = ResourceManager.GetObject("FaceWithMedicalMaskWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithThermometerApple {
            get {
                object obj = ResourceManager.GetObject("FaceWithThermometerApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithThermometerFacebook {
            get {
                object obj = ResourceManager.GetObject("FaceWithThermometerFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithThermometerGoogle {
            get {
                object obj = ResourceManager.GetObject("FaceWithThermometerGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithThermometerJoyPixels {
            get {
                object obj = ResourceManager.GetObject("FaceWithThermometerJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithThermometerSamsung {
            get {
                object obj = ResourceManager.GetObject("FaceWithThermometerSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithThermometerTwitter {
            get {
                object obj = ResourceManager.GetObject("FaceWithThermometerTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithThermometerWindows {
            get {
                object obj = ResourceManager.GetObject("FaceWithThermometerWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HotFaceApple {
            get {
                object obj = ResourceManager.GetObject("HotFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HotFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("HotFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HotFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("HotFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HotFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("HotFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HotFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("HotFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HotFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("HotFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HotFaceWindows {
            get {
                object obj = ResourceManager.GetObject("HotFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NauseatedFaceApple {
            get {
                object obj = ResourceManager.GetObject("NauseatedFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NauseatedFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("NauseatedFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NauseatedFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("NauseatedFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NauseatedFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("NauseatedFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NauseatedFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("NauseatedFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NauseatedFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("NauseatedFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NauseatedFaceWindows {
            get {
                object obj = ResourceManager.GetObject("NauseatedFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SneezingFaceApple {
            get {
                object obj = ResourceManager.GetObject("SneezingFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SneezingFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("SneezingFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SneezingFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("SneezingFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SneezingFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("SneezingFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SneezingFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("SneezingFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SneezingFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("SneezingFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SneezingFaceWindows {
            get {
                object obj = ResourceManager.GetObject("SneezingFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WoozyFaceApple {
            get {
                object obj = ResourceManager.GetObject("WoozyFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WoozyFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("WoozyFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WoozyFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("WoozyFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WoozyFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("WoozyFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WoozyFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("WoozyFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WoozyFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("WoozyFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WoozyFaceWindows {
            get {
                object obj = ResourceManager.GetObject("WoozyFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
