//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1022
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmojiLib {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FaceNegative {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FaceNegative() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmojiLib.FaceNegative", typeof(FaceNegative).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AngryFaceApple {
            get {
                object obj = ResourceManager.GetObject("AngryFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AngryFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("AngryFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AngryFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("AngryFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AngryFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("AngryFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AngryFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("AngryFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AngryFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("AngryFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AngryFaceWindows {
            get {
                object obj = ResourceManager.GetObject("AngryFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AngryFaceWithHornsApple {
            get {
                object obj = ResourceManager.GetObject("AngryFaceWithHornsApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AngryFaceWithHornsFacebook {
            get {
                object obj = ResourceManager.GetObject("AngryFaceWithHornsFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AngryFaceWithHornsGoogle {
            get {
                object obj = ResourceManager.GetObject("AngryFaceWithHornsGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AngryFaceWithHornsJoyPixels {
            get {
                object obj = ResourceManager.GetObject("AngryFaceWithHornsJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AngryFaceWithHornsSamsung {
            get {
                object obj = ResourceManager.GetObject("AngryFaceWithHornsSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AngryFaceWithHornsTwitter {
            get {
                object obj = ResourceManager.GetObject("AngryFaceWithHornsTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AngryFaceWithHornsWindows {
            get {
                object obj = ResourceManager.GetObject("AngryFaceWithHornsWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithSteamFromNoseApple {
            get {
                object obj = ResourceManager.GetObject("FaceWithSteamFromNoseApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithSteamFromNoseFacebook {
            get {
                object obj = ResourceManager.GetObject("FaceWithSteamFromNoseFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithSteamFromNoseGoogle {
            get {
                object obj = ResourceManager.GetObject("FaceWithSteamFromNoseGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithSteamFromNoseJoyPixels {
            get {
                object obj = ResourceManager.GetObject("FaceWithSteamFromNoseJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithSteamFromNoseSamsung {
            get {
                object obj = ResourceManager.GetObject("FaceWithSteamFromNoseSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithSteamFromNoseTwitter {
            get {
                object obj = ResourceManager.GetObject("FaceWithSteamFromNoseTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithSteamFromNoseWindows {
            get {
                object obj = ResourceManager.GetObject("FaceWithSteamFromNoseWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithSymbolsOnMouthApple {
            get {
                object obj = ResourceManager.GetObject("FaceWithSymbolsOnMouthApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithSymbolsOnMouthFacebook {
            get {
                object obj = ResourceManager.GetObject("FaceWithSymbolsOnMouthFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithSymbolsOnMouthGoogle {
            get {
                object obj = ResourceManager.GetObject("FaceWithSymbolsOnMouthGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithSymbolsOnMouthJoyPixels {
            get {
                object obj = ResourceManager.GetObject("FaceWithSymbolsOnMouthJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithSymbolsOnMouthSamsung {
            get {
                object obj = ResourceManager.GetObject("FaceWithSymbolsOnMouthSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithSymbolsOnMouthTwitter {
            get {
                object obj = ResourceManager.GetObject("FaceWithSymbolsOnMouthTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithSymbolsOnMouthWindows {
            get {
                object obj = ResourceManager.GetObject("FaceWithSymbolsOnMouthWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PoutingFaceApple {
            get {
                object obj = ResourceManager.GetObject("PoutingFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PoutingFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("PoutingFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PoutingFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("PoutingFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PoutingFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("PoutingFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PoutingFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("PoutingFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PoutingFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("PoutingFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PoutingFaceWindows {
            get {
                object obj = ResourceManager.GetObject("PoutingFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SkullAndCrossbonesApple {
            get {
                object obj = ResourceManager.GetObject("SkullAndCrossbonesApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SkullAndCrossbonesFacebook {
            get {
                object obj = ResourceManager.GetObject("SkullAndCrossbonesFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SkullAndCrossbonesGoogle {
            get {
                object obj = ResourceManager.GetObject("SkullAndCrossbonesGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SkullAndCrossbonesJoyPixels {
            get {
                object obj = ResourceManager.GetObject("SkullAndCrossbonesJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SkullAndCrossbonesSamsung {
            get {
                object obj = ResourceManager.GetObject("SkullAndCrossbonesSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SkullAndCrossbonesTwitter {
            get {
                object obj = ResourceManager.GetObject("SkullAndCrossbonesTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SkullAndCrossbonesWindows {
            get {
                object obj = ResourceManager.GetObject("SkullAndCrossbonesWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SkullApple {
            get {
                object obj = ResourceManager.GetObject("SkullApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SkullFacebook {
            get {
                object obj = ResourceManager.GetObject("SkullFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SkullGoogle {
            get {
                object obj = ResourceManager.GetObject("SkullGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SkullJoyPixels {
            get {
                object obj = ResourceManager.GetObject("SkullJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SkullSamsung {
            get {
                object obj = ResourceManager.GetObject("SkullSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SkullTwitter {
            get {
                object obj = ResourceManager.GetObject("SkullTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SkullWindows {
            get {
                object obj = ResourceManager.GetObject("SkullWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithHornsApple {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithHornsApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithHornsFacebook {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithHornsFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithHornsGoogle {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithHornsGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithHornsJoyPixels {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithHornsJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithHornsSamsung {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithHornsSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithHornsTwitter {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithHornsTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithHornsWindows {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithHornsWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
