//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1022
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmojiLib {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FaceNeutralSkeptical {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FaceNeutralSkeptical() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmojiLib.FaceNeutralSkeptical", typeof(FaceNeutralSkeptical).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ExpressionlessFaceApple {
            get {
                object obj = ResourceManager.GetObject("ExpressionlessFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExpressionlessFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("ExpressionlessFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExpressionlessFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("ExpressionlessFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExpressionlessFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("ExpressionlessFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExpressionlessFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("ExpressionlessFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExpressionlessFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("ExpressionlessFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExpressionlessFaceWindows {
            get {
                object obj = ResourceManager.GetObject("ExpressionlessFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithoutMouthApple {
            get {
                object obj = ResourceManager.GetObject("FaceWithoutMouthApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithoutMouthFacebook {
            get {
                object obj = ResourceManager.GetObject("FaceWithoutMouthFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithoutMouthGoogle {
            get {
                object obj = ResourceManager.GetObject("FaceWithoutMouthGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithoutMouthJoyPixels {
            get {
                object obj = ResourceManager.GetObject("FaceWithoutMouthJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithoutMouthSamsung {
            get {
                object obj = ResourceManager.GetObject("FaceWithoutMouthSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithoutMouthTwitter {
            get {
                object obj = ResourceManager.GetObject("FaceWithoutMouthTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithoutMouthWindows {
            get {
                object obj = ResourceManager.GetObject("FaceWithoutMouthWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithRaisedEyebrowApple {
            get {
                object obj = ResourceManager.GetObject("FaceWithRaisedEyebrowApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithRaisedEyebrowFacebook {
            get {
                object obj = ResourceManager.GetObject("FaceWithRaisedEyebrowFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithRaisedEyebrowGoogle {
            get {
                object obj = ResourceManager.GetObject("FaceWithRaisedEyebrowGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithRaisedEyebrowJoyPixels {
            get {
                object obj = ResourceManager.GetObject("FaceWithRaisedEyebrowJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithRaisedEyebrowSamsung {
            get {
                object obj = ResourceManager.GetObject("FaceWithRaisedEyebrowSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithRaisedEyebrowTwitter {
            get {
                object obj = ResourceManager.GetObject("FaceWithRaisedEyebrowTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithRaisedEyebrowWindows {
            get {
                object obj = ResourceManager.GetObject("FaceWithRaisedEyebrowWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithRollingEyesApple {
            get {
                object obj = ResourceManager.GetObject("FaceWithRollingEyesApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithRollingEyesFacebook {
            get {
                object obj = ResourceManager.GetObject("FaceWithRollingEyesFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithRollingEyesGoogle {
            get {
                object obj = ResourceManager.GetObject("FaceWithRollingEyesGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithRollingEyesJoyPixels {
            get {
                object obj = ResourceManager.GetObject("FaceWithRollingEyesJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithRollingEyesSamsung {
            get {
                object obj = ResourceManager.GetObject("FaceWithRollingEyesSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithRollingEyesTwitter {
            get {
                object obj = ResourceManager.GetObject("FaceWithRollingEyesTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithRollingEyesWindows {
            get {
                object obj = ResourceManager.GetObject("FaceWithRollingEyesWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrimacingFaceApple {
            get {
                object obj = ResourceManager.GetObject("GrimacingFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrimacingFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("GrimacingFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrimacingFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("GrimacingFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrimacingFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("GrimacingFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrimacingFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("GrimacingFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrimacingFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("GrimacingFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrimacingFaceWindows {
            get {
                object obj = ResourceManager.GetObject("GrimacingFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LyingFaceApple {
            get {
                object obj = ResourceManager.GetObject("LyingFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LyingFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("LyingFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LyingFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("LyingFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LyingFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("LyingFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LyingFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("LyingFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LyingFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("LyingFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LyingFaceWindows {
            get {
                object obj = ResourceManager.GetObject("LyingFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NeutralFaceApple {
            get {
                object obj = ResourceManager.GetObject("NeutralFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NeutralFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("NeutralFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NeutralFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("NeutralFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NeutralFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("NeutralFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NeutralFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("NeutralFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NeutralFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("NeutralFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NeutralFaceWindows {
            get {
                object obj = ResourceManager.GetObject("NeutralFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmirkingFaceApple {
            get {
                object obj = ResourceManager.GetObject("SmirkingFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmirkingFaceDocomo {
            get {
                object obj = ResourceManager.GetObject("SmirkingFaceDocomo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmirkingFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("SmirkingFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmirkingFaceGmail {
            get {
                object obj = ResourceManager.GetObject("SmirkingFaceGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmirkingFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("SmirkingFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmirkingFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("SmirkingFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmirkingFaceKddi {
            get {
                object obj = ResourceManager.GetObject("SmirkingFaceKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmirkingFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("SmirkingFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmirkingFaceSoftbank {
            get {
                object obj = ResourceManager.GetObject("SmirkingFaceSoftbank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmirkingFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("SmirkingFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmirkingFaceWindows {
            get {
                object obj = ResourceManager.GetObject("SmirkingFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UnamusedFaceApple {
            get {
                object obj = ResourceManager.GetObject("UnamusedFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UnamusedFaceDocomo {
            get {
                object obj = ResourceManager.GetObject("UnamusedFaceDocomo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UnamusedFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("UnamusedFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UnamusedFaceGmail {
            get {
                object obj = ResourceManager.GetObject("UnamusedFaceGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UnamusedFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("UnamusedFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UnamusedFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("UnamusedFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UnamusedFaceKddi {
            get {
                object obj = ResourceManager.GetObject("UnamusedFaceKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UnamusedFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("UnamusedFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UnamusedFaceSoftbank {
            get {
                object obj = ResourceManager.GetObject("UnamusedFaceSoftbank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UnamusedFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("UnamusedFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UnamusedFaceWindows {
            get {
                object obj = ResourceManager.GetObject("UnamusedFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZipperMouthFaceApple {
            get {
                object obj = ResourceManager.GetObject("ZipperMouthFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZipperMouthFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("ZipperMouthFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZipperMouthFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("ZipperMouthFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZipperMouthFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("ZipperMouthFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZipperMouthFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("ZipperMouthFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZipperMouthFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("ZipperMouthFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZipperMouthFaceWindows {
            get {
                object obj = ResourceManager.GetObject("ZipperMouthFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
