//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1022
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmojiLib {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FaceGlasses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FaceGlasses() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmojiLib.FaceGlasses", typeof(FaceGlasses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithMonocleApple {
            get {
                object obj = ResourceManager.GetObject("FaceWithMonocleApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithMonocleFacebook {
            get {
                object obj = ResourceManager.GetObject("FaceWithMonocleFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithMonocleGoogle {
            get {
                object obj = ResourceManager.GetObject("FaceWithMonocleGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithMonocleJoyPixels {
            get {
                object obj = ResourceManager.GetObject("FaceWithMonocleJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithMonocleSamsung {
            get {
                object obj = ResourceManager.GetObject("FaceWithMonocleSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithMonocleTwitter {
            get {
                object obj = ResourceManager.GetObject("FaceWithMonocleTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithMonocleWindows {
            get {
                object obj = ResourceManager.GetObject("FaceWithMonocleWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NerdFaceApple {
            get {
                object obj = ResourceManager.GetObject("NerdFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NerdFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("NerdFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NerdFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("NerdFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NerdFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("NerdFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NerdFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("NerdFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NerdFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("NerdFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NerdFaceWindows {
            get {
                object obj = ResourceManager.GetObject("NerdFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithSunglassesApple {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithSunglassesApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithSunglassesFacebook {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithSunglassesFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithSunglassesGmail {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithSunglassesGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithSunglassesGoogle {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithSunglassesGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithSunglassesJoyPixels {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithSunglassesJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithSunglassesSamsung {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithSunglassesSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithSunglassesTwitter {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithSunglassesTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithSunglassesWindows {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithSunglassesWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
