//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1022
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmojiLib {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FaceSleepy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FaceSleepy() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmojiLib.FaceSleepy", typeof(FaceSleepy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap DroolingFaceApple {
            get {
                object obj = ResourceManager.GetObject("DroolingFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DroolingFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("DroolingFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DroolingFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("DroolingFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DroolingFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("DroolingFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DroolingFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("DroolingFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DroolingFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("DroolingFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DroolingFaceWindows {
            get {
                object obj = ResourceManager.GetObject("DroolingFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PensiveFaceApple {
            get {
                object obj = ResourceManager.GetObject("PensiveFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PensiveFaceDocomo {
            get {
                object obj = ResourceManager.GetObject("PensiveFaceDocomo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PensiveFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("PensiveFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PensiveFaceGmail {
            get {
                object obj = ResourceManager.GetObject("PensiveFaceGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PensiveFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("PensiveFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PensiveFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("PensiveFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PensiveFaceKddi {
            get {
                object obj = ResourceManager.GetObject("PensiveFaceKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PensiveFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("PensiveFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PensiveFaceSoftbank {
            get {
                object obj = ResourceManager.GetObject("PensiveFaceSoftbank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PensiveFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("PensiveFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PensiveFaceWindows {
            get {
                object obj = ResourceManager.GetObject("PensiveFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RelievedFaceApple {
            get {
                object obj = ResourceManager.GetObject("RelievedFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RelievedFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("RelievedFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RelievedFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("RelievedFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RelievedFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("RelievedFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RelievedFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("RelievedFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RelievedFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("RelievedFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RelievedFaceWindows {
            get {
                object obj = ResourceManager.GetObject("RelievedFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RrelievedFaceDocomo {
            get {
                object obj = ResourceManager.GetObject("RrelievedFaceDocomo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RrelievedFaceGmail {
            get {
                object obj = ResourceManager.GetObject("RrelievedFaceGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RrelievedFaceKddi {
            get {
                object obj = ResourceManager.GetObject("RrelievedFaceKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RrelievedFaceSoftbank {
            get {
                object obj = ResourceManager.GetObject("RrelievedFaceSoftbank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SleepingFaceApple {
            get {
                object obj = ResourceManager.GetObject("SleepingFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SleepingFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("SleepingFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SleepingFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("SleepingFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SleepingFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("SleepingFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SleepingFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("SleepingFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SleepingFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("SleepingFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SleepingFaceWindows {
            get {
                object obj = ResourceManager.GetObject("SleepingFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SleepyFaceApple {
            get {
                object obj = ResourceManager.GetObject("SleepyFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SleepyFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("SleepyFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SleepyFaceGmail {
            get {
                object obj = ResourceManager.GetObject("SleepyFaceGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SleepyFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("SleepyFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SleepyFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("SleepyFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SleepyFaceKddi {
            get {
                object obj = ResourceManager.GetObject("SleepyFaceKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SleepyFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("SleepyFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SleepyFaceSoftbank {
            get {
                object obj = ResourceManager.GetObject("SleepyFaceSoftbank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SleepyFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("SleepyFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SleepyFaceWindows {
            get {
                object obj = ResourceManager.GetObject("SleepyFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
