//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1022
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmojiLib {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FaceAffection {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FaceAffection() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmojiLib.FaceAffection", typeof(FaceAffection).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap FaceBlowingAKissApple {
            get {
                object obj = ResourceManager.GetObject("FaceBlowingAKissApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceBlowingAKissFacebook {
            get {
                object obj = ResourceManager.GetObject("FaceBlowingAKissFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceBlowingAKissGoogle {
            get {
                object obj = ResourceManager.GetObject("FaceBlowingAKissGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceBlowingAKissJoyPixels {
            get {
                object obj = ResourceManager.GetObject("FaceBlowingAKissJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceBlowingAKissSamsung {
            get {
                object obj = ResourceManager.GetObject("FaceBlowingAKissSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceBlowingAKissTwitter {
            get {
                object obj = ResourceManager.GetObject("FaceBlowingAKissTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceBlowingAKissWindows {
            get {
                object obj = ResourceManager.GetObject("FaceBlowingAKissWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingFaceApple {
            get {
                object obj = ResourceManager.GetObject("KissingFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("KissingFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("KissingFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("KissingFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("KissingFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("KissingFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingFaceWindows {
            get {
                object obj = ResourceManager.GetObject("KissingFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingFaceWithClosedEyesApple {
            get {
                object obj = ResourceManager.GetObject("KissingFaceWithClosedEyesApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingFaceWithClosedEyesFacebook {
            get {
                object obj = ResourceManager.GetObject("KissingFaceWithClosedEyesFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingFaceWithClosedEyesGoogle {
            get {
                object obj = ResourceManager.GetObject("KissingFaceWithClosedEyesGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingFaceWithClosedEyesJoyPixels {
            get {
                object obj = ResourceManager.GetObject("KissingFaceWithClosedEyesJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingFaceWithClosedEyesSamsung {
            get {
                object obj = ResourceManager.GetObject("KissingFaceWithClosedEyesSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingFaceWithClosedEyesTwitter {
            get {
                object obj = ResourceManager.GetObject("KissingFaceWithClosedEyesTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingFaceWithClosedEyesWindows {
            get {
                object obj = ResourceManager.GetObject("KissingFaceWithClosedEyesWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingFaceWithSmilingEyesApple {
            get {
                object obj = ResourceManager.GetObject("KissingFaceWithSmilingEyesApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingFaceWithSmilingEyesFacebook {
            get {
                object obj = ResourceManager.GetObject("KissingFaceWithSmilingEyesFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingFaceWithSmilingEyesGoogle {
            get {
                object obj = ResourceManager.GetObject("KissingFaceWithSmilingEyesGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingFaceWithSmilingEyesJoyPixels {
            get {
                object obj = ResourceManager.GetObject("KissingFaceWithSmilingEyesJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingFaceWithSmilingEyesSamsung {
            get {
                object obj = ResourceManager.GetObject("KissingFaceWithSmilingEyesSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingFaceWithSmilingEyesTwitter {
            get {
                object obj = ResourceManager.GetObject("KissingFaceWithSmilingEyesTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KissingFaceWithSmilingEyesWindows {
            get {
                object obj = ResourceManager.GetObject("KissingFaceWithSmilingEyesWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceApple {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWindows {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithHeartEyesApple {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithHeartEyesApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithHeartEyesFacebook {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithHeartEyesFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithHeartEyesGoogle {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithHeartEyesGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithHeartEyesJoyPixels {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithHeartEyesJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithHeartEyesSamsung {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithHeartEyesSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithHeartEyesTwitter {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithHeartEyesTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithHeartEyesWindows {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithHeartEyesWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithHeartsApple {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithHeartsApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithHeartsFacebook {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithHeartsFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithHeartsGoogle {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithHeartsGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithHeartsJoyPixels {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithHeartsJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithHeartsSamsung {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithHeartsSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithHeartsTwitter {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithHeartsTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithHeartsWindows {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithHeartsWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithTearGoogle {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithTearGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmilingFaceWithTearJoyPixels {
            get {
                object obj = ResourceManager.GetObject("SmilingFaceWithTearJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StarStruckApple {
            get {
                object obj = ResourceManager.GetObject("StarStruckApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StarStruckFacebook {
            get {
                object obj = ResourceManager.GetObject("StarStruckFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StarStruckGoogle {
            get {
                object obj = ResourceManager.GetObject("StarStruckGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StarStruckJoyPixels {
            get {
                object obj = ResourceManager.GetObject("StarStruckJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StarStruckSamsung {
            get {
                object obj = ResourceManager.GetObject("StarStruckSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StarStruckTwitter {
            get {
                object obj = ResourceManager.GetObject("StarStruckTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StarStruckWindows {
            get {
                object obj = ResourceManager.GetObject("StarStruckWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
