//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1022
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmojiLib {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FaceTongue {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FaceTongue() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmojiLib.FaceTongue", typeof(FaceTongue).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap FaceSavoringFoodApple {
            get {
                object obj = ResourceManager.GetObject("FaceSavoringFoodApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceSavoringFoodFacebook {
            get {
                object obj = ResourceManager.GetObject("FaceSavoringFoodFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceSavoringFoodGoogle {
            get {
                object obj = ResourceManager.GetObject("FaceSavoringFoodGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceSavoringFoodJoyPixels {
            get {
                object obj = ResourceManager.GetObject("FaceSavoringFoodJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceSavoringFoodSamsung {
            get {
                object obj = ResourceManager.GetObject("FaceSavoringFoodSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceSavoringFoodTwitter {
            get {
                object obj = ResourceManager.GetObject("FaceSavoringFoodTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceSavoringFoodWindows {
            get {
                object obj = ResourceManager.GetObject("FaceSavoringFoodWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithTongueApple {
            get {
                object obj = ResourceManager.GetObject("FaceWithTongueApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithTongueFacebook {
            get {
                object obj = ResourceManager.GetObject("FaceWithTongueFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithTongueGoogle {
            get {
                object obj = ResourceManager.GetObject("FaceWithTongueGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithTongueJoyPixels {
            get {
                object obj = ResourceManager.GetObject("FaceWithTongueJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithTongueSamsung {
            get {
                object obj = ResourceManager.GetObject("FaceWithTongueSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithTongueTwitter {
            get {
                object obj = ResourceManager.GetObject("FaceWithTongueTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaceWithTongueWindows {
            get {
                object obj = ResourceManager.GetObject("FaceWithTongueWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MoneyMouthFaceApple {
            get {
                object obj = ResourceManager.GetObject("MoneyMouthFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MoneyMouthFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("MoneyMouthFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MoneyMouthFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("MoneyMouthFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MoneyMouthFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("MoneyMouthFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MoneyMouthFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("MoneyMouthFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MoneyMouthFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("MoneyMouthFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MoneyMouthFaceWindows {
            get {
                object obj = ResourceManager.GetObject("MoneyMouthFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SquintingFaceWithTongueApple {
            get {
                object obj = ResourceManager.GetObject("SquintingFaceWithTongueApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SquintingFaceWithTongueFacebook {
            get {
                object obj = ResourceManager.GetObject("SquintingFaceWithTongueFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SquintingFaceWithTongueGmail {
            get {
                object obj = ResourceManager.GetObject("SquintingFaceWithTongueGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SquintingFaceWithTongueGoogle {
            get {
                object obj = ResourceManager.GetObject("SquintingFaceWithTongueGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SquintingFaceWithTongueJoyPixels {
            get {
                object obj = ResourceManager.GetObject("SquintingFaceWithTongueJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SquintingFaceWithTongueSamsung {
            get {
                object obj = ResourceManager.GetObject("SquintingFaceWithTongueSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SquintingFaceWithTongueSoftbank {
            get {
                object obj = ResourceManager.GetObject("SquintingFaceWithTongueSoftbank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SquintingFaceWithTongueTwitter {
            get {
                object obj = ResourceManager.GetObject("SquintingFaceWithTongueTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SquintingFaceWithTongueWindows {
            get {
                object obj = ResourceManager.GetObject("SquintingFaceWithTongueWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WinkingFaceWithTongueApple {
            get {
                object obj = ResourceManager.GetObject("WinkingFaceWithTongueApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WinkingFaceWithTongueDocomo {
            get {
                object obj = ResourceManager.GetObject("WinkingFaceWithTongueDocomo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WinkingFaceWithTongueFacebook {
            get {
                object obj = ResourceManager.GetObject("WinkingFaceWithTongueFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WinkingFaceWithTongueGmail {
            get {
                object obj = ResourceManager.GetObject("WinkingFaceWithTongueGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WinkingFaceWithTongueGoogle {
            get {
                object obj = ResourceManager.GetObject("WinkingFaceWithTongueGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WinkingFaceWithTongueJoyPixels {
            get {
                object obj = ResourceManager.GetObject("WinkingFaceWithTongueJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WinkingFaceWithTongueKddi {
            get {
                object obj = ResourceManager.GetObject("WinkingFaceWithTongueKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WinkingFaceWithTongueSamsung {
            get {
                object obj = ResourceManager.GetObject("WinkingFaceWithTongueSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WinkingFaceWithTongueSoftbank {
            get {
                object obj = ResourceManager.GetObject("WinkingFaceWithTongueSoftbank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WinkingFaceWithTongueTwitter {
            get {
                object obj = ResourceManager.GetObject("WinkingFaceWithTongueTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WinkingFaceWithTongueWindows {
            get {
                object obj = ResourceManager.GetObject("WinkingFaceWithTongueWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZanyFaceApple {
            get {
                object obj = ResourceManager.GetObject("ZanyFaceApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZanyFaceFacebook {
            get {
                object obj = ResourceManager.GetObject("ZanyFaceFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZanyFaceGoogle {
            get {
                object obj = ResourceManager.GetObject("ZanyFaceGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZanyFaceJoyPixels {
            get {
                object obj = ResourceManager.GetObject("ZanyFaceJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZanyFaceSamsung {
            get {
                object obj = ResourceManager.GetObject("ZanyFaceSamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZanyFaceTwitter {
            get {
                object obj = ResourceManager.GetObject("ZanyFaceTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZanyFaceWindows {
            get {
                object obj = ResourceManager.GetObject("ZanyFaceWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
