//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1022
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmojiLib {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MonkeyFace {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MonkeyFace() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmojiLib.MonkeyFace", typeof(MonkeyFace).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap HearNoEvilMonkeyApple {
            get {
                object obj = ResourceManager.GetObject("HearNoEvilMonkeyApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HearNoEvilMonkeyFacebook {
            get {
                object obj = ResourceManager.GetObject("HearNoEvilMonkeyFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HearNoEvilMonkeyGmail {
            get {
                object obj = ResourceManager.GetObject("HearNoEvilMonkeyGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HearNoEvilMonkeyGoogle {
            get {
                object obj = ResourceManager.GetObject("HearNoEvilMonkeyGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HearNoEvilMonkeyJoyPixels {
            get {
                object obj = ResourceManager.GetObject("HearNoEvilMonkeyJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HearNoEvilMonkeyKddi {
            get {
                object obj = ResourceManager.GetObject("HearNoEvilMonkeyKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HearNoEvilMonkeySamsung {
            get {
                object obj = ResourceManager.GetObject("HearNoEvilMonkeySamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HearNoEvilMonkeyTwitter {
            get {
                object obj = ResourceManager.GetObject("HearNoEvilMonkeyTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HearNoEvilMonkeyWindows {
            get {
                object obj = ResourceManager.GetObject("HearNoEvilMonkeyWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SeeNoEvilMonkeyApple {
            get {
                object obj = ResourceManager.GetObject("SeeNoEvilMonkeyApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SeeNoEvilMonkeyFacebook {
            get {
                object obj = ResourceManager.GetObject("SeeNoEvilMonkeyFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SeeNoEvilMonkeyGmail {
            get {
                object obj = ResourceManager.GetObject("SeeNoEvilMonkeyGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SeeNoEvilMonkeyGoogle {
            get {
                object obj = ResourceManager.GetObject("SeeNoEvilMonkeyGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SeeNoEvilMonkeyJoyPixels {
            get {
                object obj = ResourceManager.GetObject("SeeNoEvilMonkeyJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SeeNoEvilMonkeyKddi {
            get {
                object obj = ResourceManager.GetObject("SeeNoEvilMonkeyKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SeeNoEvilMonkeySamsung {
            get {
                object obj = ResourceManager.GetObject("SeeNoEvilMonkeySamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SeeNoEvilMonkeyTwitter {
            get {
                object obj = ResourceManager.GetObject("SeeNoEvilMonkeyTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SeeNoEvilMonkeyWindows {
            get {
                object obj = ResourceManager.GetObject("SeeNoEvilMonkeyWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpeakNoEvilMonkeyApple {
            get {
                object obj = ResourceManager.GetObject("SpeakNoEvilMonkeyApple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpeakNoEvilMonkeyFacebook {
            get {
                object obj = ResourceManager.GetObject("SpeakNoEvilMonkeyFacebook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpeakNoEvilMonkeyGmail {
            get {
                object obj = ResourceManager.GetObject("SpeakNoEvilMonkeyGmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpeakNoEvilMonkeyGoogle {
            get {
                object obj = ResourceManager.GetObject("SpeakNoEvilMonkeyGoogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpeakNoEvilMonkeyJoyPixels {
            get {
                object obj = ResourceManager.GetObject("SpeakNoEvilMonkeyJoyPixels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpeakNoEvilMonkeyKddi {
            get {
                object obj = ResourceManager.GetObject("SpeakNoEvilMonkeyKddi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpeakNoEvilMonkeySamsung {
            get {
                object obj = ResourceManager.GetObject("SpeakNoEvilMonkeySamsung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpeakNoEvilMonkeyTwitter {
            get {
                object obj = ResourceManager.GetObject("SpeakNoEvilMonkeyTwitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpeakNoEvilMonkeyWindows {
            get {
                object obj = ResourceManager.GetObject("SpeakNoEvilMonkeyWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
